a = input("Digite algo: ")
print("O tipo primitivo desse valor é ", type(a))
print("É numérico:", a.isnumeric())
print("É alfabético:", a.isalpha())
print("É maiúsculo:", a.isupper())
print("É minúsculo:", a.islower())
print("É alfanumérico:", a.isalnum())
print("É decimal:", a.isdecimal())
print("É dígito:", a.isdigit())
print("É imprimível:", a.isprintable())
print("É espaço em branco:", a.isspace())
print("É título:", a.istitle())
print("É um identificador válido:", a.isidentifier())